version: "3.1"

services:
  server:
    image: nginx
    ports:
      - ${APPLICATION_PORT:-9255}:443
    volumes:
      - /opt/openvidu/certificates/live/ov-test-fullsize.naevatec.com/fullchain.pem:/opt/openvidu/certificates/live/ov-test-fullsize.naevatec.com/fullchain.pem:ro
      - /opt/openvidu/certificates/live/ov-test-fullsize.naevatec.com/privkey.pem:/opt/openvidu/certificates/live/ov-test-fullsize.naevatec.com/privkey.pem:ro
      - ./data/nginx/default.conf:/etc/nginx/nginx.conf
      - ./data/logs/:/var/log/nginx
    networks:
      net:
        aliases:
          - web

networks:
  net:

